figure
subplot(2,2,[1])
stairs(zmienne_stanu.time,zmienne_stanu.signals(3).values,'r')
title('zmienna stanu x3(t)')
xlabel('t[s]')
subplot(2,2,[2])
stairs(zmienne_stanu.time,zmienne_stanu.signals(2).values,'m')
title('zmienna stanu x2(t)')
xlabel('t[s]')
subplot(2,2,[3])
stairs(zmienne_stanu.time,zmienne_stanu.signals(1).values,'b')
title('zmienna stanu x1(t) = y(t)')
xlabel('t[s]')
subplot(2,2,[4])
stairs(wyjscie_sterowanie.time,wyjscie_sterowanie.signals(1).values)
title('sterowanie')
xlabel('t[s]')
